# Generated by Django 5.2 on 2025-08-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekendApp', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='villa_or_resort',
        ),
        migrations.AddField(
            model_name='booking',
            name='pg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='WeekendApp.pg'),
        ),
    ]
