# Generated by Django 5.2 on 2025-08-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeekendApp', '0003_remove_booking_villa_or_resort_booking_pg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='college',
        ),
        migrations.DeleteModel(
            name='college',
        ),
    ]
