# Generated by Django 5.2 on 2025-08-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekendApp', '0004_remove_pg_college_delete_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeekendApp.pg'),
        ),
    ]
