# Generated by Django 5.2 on 2025-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekendApp', '0007_feedback_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='nearest_police_station',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='nearest_hospital',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),

    ]
