# Generated by Django 5.2 on 2025-10-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeekendApp', '0008_pg_nearest_hospital_pg_nearest_police_station'),
    ]

    operations = [
    ]
